# Listen Port
server:
  address: "0.0.0.0:10061"


# Influxdb Server
influxdb:
  url: "http://192.168.1.100:8086"
  token: "6xbs-nUI6oQjDvhUSUc8VBtzdvl324yY5JdKYv9enGrDrwf4jhjYTaiaAxHWRJzQchodRMVdaBJRnLsNzruUUA=="
  org: "test"
  bucket: "tels"


# Redis Server
redis:
  address: "127.0.0.1:6379"